'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmpNPS
    
    '''<summary>
    '''enterJobsGridNoJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents enterJobsGridNoJobs As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gridNPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridNPS As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtEnterNPSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnterNPSDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnterNPSTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnterNPSPromoter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSPromoter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnterNPSPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSPass As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnterNPSDetractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnterNPSDetractor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEnterNPSError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnterNPSError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNPSSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNPSSave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkNPSNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNPSNew As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReturn As Global.System.Web.UI.WebControls.LinkButton
End Class
