'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Landing
    
    '''<summary>
    '''litLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLinks As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''teamWelcomeUpdateNPSButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeUpdateNPSButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUpdateNPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateNPS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEmpNPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpNPS As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkUpdateNPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUpdateNPS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkPayrollAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPayrollAdjustments As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''teamWelcomeEditTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeEditTruckHoursMin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTruckHoursMin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTruckHoursMin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkUpdateTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUpdateTruckHoursMin As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''teamWelcomeEditTruckHoursMinReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeEditTruckHoursMinReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl30Day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl30Day As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt30DayTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt30DayTruckHoursMin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl90Day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl90Day As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt90DayTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt90DayTruckHoursMin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblYTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYTD As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtYTDTruckHoursMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYTDTruckHoursMin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkUpdateTruckHoursMinReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUpdateTruckHoursMinReport As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''teamWelcomeEditRouteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeEditRouteButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlEditRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditRoute As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''teamWelcomeRouteAssignmentsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeRouteAssignmentsButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlRouteAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRouteAssignments As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkGoRouteAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGoRouteAssignment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''teamWelcomeCreateRouteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeCreateRouteButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtCreateRouteNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreateRouteNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCreateRouteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreateRouteDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkCreateRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateRoute As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCreateError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''teamWelcomeDeleteRouteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamWelcomeDeleteRouteButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDeleteRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDeleteRoute As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkDeleteRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeleteRoute As Global.System.Web.UI.WebControls.LinkButton
End Class
