'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportsView
    
    '''<summary>
    '''lnkReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReturn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updateReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateReports As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''litCECReportsView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCECReportsView As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlCECReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCECReport As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdCECResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCECResults As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtCECStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCECStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCECEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCECEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkCECSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCECSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlJobsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlJobsReport As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdJobs As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtJobsStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobsStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJobsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkJobsSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkJobsSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPayroll As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPayroll As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdPayrollSecondWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPayrollSecondWeek As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdPayrollTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPayrollTotal As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtPayrollStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayrollStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPayrollSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPayrollSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlPayrollDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPayrollDates As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdPayrollDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPayrollDates As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlRPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRPH As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdRPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRPH As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdRPHNotMet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRPHNotMet As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtRPHStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPHStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRPHEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPHEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkRPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRPH As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSign As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdSigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSigns As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdSignsNoMinimum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSignsNoMinimum As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtSignsStarDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignsStarDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSignsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkSigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSigns As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTips As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTips As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtTipsStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipsStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTipsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTips As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlTopDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopDog As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdTopDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTopDog As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtTopDogStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopDogEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTopDogSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopDogSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlTopDogV2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopDogV2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdViewTopDogV2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewTopDogV2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtTopDogV2StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV2StartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopDogV2EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV2EndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTopDogV2Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopDogV2Submit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlTopDogV3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopDogV3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdTopDogV3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTopDogV3 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtTopDogV3StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV3StartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopDogV3EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV3EndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTopDogV3Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopDogV3Submit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlEmployeeMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmployeeMetrics As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdEmployeeMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdEmployeeMetrics As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtEmployeeMetricsStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeMetricsStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkEmployeeMetricsSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEmployeeMetricsSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlAJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAJS As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdAJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAJS As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtAJSStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJSStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAJSEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJSEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkAJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAJS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlHourType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHourType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdHourType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdHourType As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtHourTypeStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHourTypeStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHourTypeEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHourTypeEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkHourTypeSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHourTypeSubmit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlReasonNotConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReasonNotConvert As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdReasonsNotConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdReasonsNotConvert As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtReasonNotConvertStateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonNotConvertStateDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReasonNotConvertEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonNotConvertEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkReasonNotConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReasonNotConvert As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlDailyRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDailyRoute As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdDailyRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDailyRoute As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtDailyRouteStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDailyRouteStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkDailyRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDailyRoute As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlDumpLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDumpLocation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdDumpLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDumpLocation As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlGasLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGasLocation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdGasLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdGasLocation As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlOSCbyGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOSCbyGuy As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdOSCbyGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOSCbyGuy As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlOSCGuyResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOSCGuyResults As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdOSCGuyResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOSCGuyResults As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlDumpsByGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDumpsByGuy As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdDumpsByGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDumpsByGuy As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlDumpsByGuyResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDumpsByGuyResults As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdDumpsByGuyResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDumpsByGuyResults As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlDiscountsGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDiscountsGuy As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdDiscountsGuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDiscountsGuy As Global.System.Web.UI.WebControls.GridView
End Class
