'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reports
    
    '''<summary>
    '''txtCECStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCECStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCECEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCECEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkCEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCEC As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtJobsStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobsStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJobsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkJobs As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtPayrollStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayrollStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPayroll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtPayrollDatesStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayrollDatesStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPayrollDatesEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayrollDatesEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPayrollDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPayrollDates As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtRPHStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPHStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRPHEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPHEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkRPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRPH As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtSignsStarDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignsStarDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSignsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkSigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSigns As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtTopDogStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopDogEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTopDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopDog As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtTipsStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipsStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTipsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipsEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTips As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtMetricsAsOfDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMetricsAsOfDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkMetricsScorecard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMetricsScorecard As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtAJSStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJSStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAJSEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJSEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkAJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAJS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtTopDogV2StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV2StartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopDogV2EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopDogV2EndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkTopDogV2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopDogV2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReturn As Global.System.Web.UI.WebControls.LinkButton
End Class
