'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Top5

    '''<summary>
    '''lblRouteNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRouteNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTodaysDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodaysDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGoal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGoal1Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal1Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal2Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal2Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal3Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal3Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal4Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal4Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoal5Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal5Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave1Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave1Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave2Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave2Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWave3Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWave3Value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTruckLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTruckLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBoxSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBoxSpace As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTruckNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTruckNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
